#!/bin/bash
######################################################################################################################################
####################################### No Changes to this part of the batch #########################################################
######################################################################################################################################

#SBATCH --partition rtx3070			### Specify partition name where to run a job.
#SBATCH --time 0-00:01:00			### Job running time limit. Make sure it is not exceeding the partition time limit! Format: D-H:MM:SS
#SBATCH --output job-%J.out			### Output log for running job - %J is the job number variable
#SBATCH --error job-%J.err			### Output log for running job - %J is the job number variable
#SBATCH --gres=gpu:1       	        ### number of GPUs, ask for more than 1 only if you can parallelize your code for multi GPU
#SBATCH --cpus-per-task=8    		### number of CPU cores
#######################################################################################################################################


######################################################################################################################################
####################################### Start you code below ####  ###################################################################
######################################################################################################################################

#SBATCH --job-name 'integration'		### Name of the job. replace my_job with your desired job name
#SBATCH --nodes 4
#SBATCH --ntasks-per-node=1
#SBATCH --ntasks=4

module load anaconda  			### load anaconda module (must present when working with conda environments)
source activate integration_dev ### activating environment, environment must be configured before running the job


mpicc -fopenmp -c mpi_driver.c -o mpi_driver.o
mpicc -c io_reader.c -o io_reader.o
mpicc -fopenmp -c matcher_omp_wrapper.c -o matcher_omp_wrapper.o
nvcc -c matcher_cuda_per_object.cu -o matcher_cuda_per_object.o

mpicxx -fopenmp -o matcher mpi_driver.o io_reader.o matcher_omp_wrapper.o matcher_cuda_per_object.o -L/usr/local/cuda/lib -L/usr/local/cuda/lib64 -lcudart	

mpirun ./matcher
